import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../src/components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar/>
      <Head>
        <title>Crypto Bond Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NUS Fintech Society Winter Project - Crypto Bonds Service
        </h1>

        <p className={styles.description}>
          Insert your part into {' '}
          pages/index.tsx
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>View Bonds &rarr;</h2>
            <p>Users can view all the available bonds on the market</p>
          </a>

          <a href="#"  className={styles.card}>
            <h2>Buy Bonds &rarr;</h2>
            <p>Users can buy bonds available on the market</p>
          </a>

          <a
            href="#" 
            className={styles.card}
          >
            <h2>Redeem Bonds &rarr;</h2>
            <p>Users can redeem rewards from holding the bonds</p>
          </a>

          <a
            href="#" 
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>DashBoard or smth else &rarr;</h2>
            <p>
              Maybe can be like some overview of an user stats
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
